[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
tyt_transfer_hook = "BEFYxWjzadyjmYQvpuvaLjZnbeE2Q9daN3Z8FDC3jCBL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/tyt_transfer_hook"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
